### ISSUE TITLE
Change the default password length to 16 characters

### ISSUE THREAD

**Issue by devshawn** [devshawn/password.live#19]
Increasing to length 16 increases "time to crack" by more than a factor of 300,000,000 (based on baselines from https://github.com/howsecureismypassword/hsimp).

So, let's change the default length to 16 within the server.

**Comment by Apoorva-13** [comment]
can i take this up??

**Comment by devshawn** [comment]
@Apoorva-13 - Yess you can!

**Comment by Apoorva-13** [comment]
@devshawn pls guide me where am i going wrong.

**Comment by Apoorva-13** [comment]
@devshawn where and what all changes are needed , i am new to this ,would need some guidance pls.

**Comment by stripedpajamas** [comment]
@Apoorva-13 I think the build is failing because there is also a test associated with the default password length that needs updating... check out this file https://github.com/devshawn/password.live/blob/master/source/server/__tests__/services/password.service.spec.js#L9

**Comment by ulziibuyan** [comment]
Sorry @Apoorva-13, I did not see you took over this issue. My PR passed the check. You can look at it as an example.

**Comment by ulziibuyan** [comment]
@Apoorva-13: You're right. I formally apologize. You probably commented after I started working on it. Anyways, I'll close my PR.

**Comment by devshawn** [comment]
Thanks @Apoorva-13 & @ulziibuyan for giving it a shot! :)
